/* Atlas Forge: a browser-native spherical procedural world generator. */
const $=id=>document.getElementById(id), map=$('mapCanvas'), globe=$('globeCanvas'), ctx=map.getContext('2d'), gctx=globe.getContext('2d');
let worlds=[], layer='terrain', view='map', phase=0;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)); const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function v3(lat,lon){const c=Math.cos(lat);return [c*Math.cos(lon),Math.sin(lat),c*Math.sin(lon)]}
function rotate(p,axis,angle){const c=Math.cos(angle),s=Math.sin(angle),d=dot(axis,p);return [p[0]*c+(axis[1]*p[2]-axis[2]*p[1])*s+axis[0]*d*(1-c),p[1]*c+(axis[2]*p[0]-axis[0]*p[2])*s+axis[1]*d*(1-c),p[2]*c+(axis[0]*p[1]-axis[1]*p[0])*s+axis[2]*d*(1-c)]}
function noise(p,seed){let n=Math.sin(dot(p,[12.9898,78.233,37.719])*43758.5453+seed*0.00031)*43758.5453;return n-Math.floor(n)}
function fractal(p,seed){let s=0,w=1,sum=0;for(let k=1;k<5;k++){let q=[p[0]*k*2.13,p[1]*k*1.71,p[2]*k*2.71];s+=(noise(q,seed+k*91)*2-1)*w;sum+=w;w*=.51}return s/sum}
function cfg(){return {name:$('planetName').value,seed:+$('seed').value||1,w:+$('width').value,h:+$('height').value,plates:+$('plates').value,land:+$('land').value/100,mountains:+$('mountains').value/100,micro:+$('micro').value,steps:+$('steps').value,years:+$('years').value,drift:+$('drift').value/100,tile:+$('tileRes').value,similar:+$('similarity').value/100,tilt:+$('tilt').value}}
function makeSeeds(c){const r=rng(c.seed),a=[];for(let i=0;i<c.plates+c.micro;i++){let z=r()*2-1,lon=r()*Math.PI*2-Math.PI,lat=Math.asin(z),p=v3(lat,lon);let ax=[r()*2-1,r()*2-1,r()*2-1],l=Math.hypot(...ax);ax=ax.map(x=>x/l);a.push({p,axis:ax,continental:r()<c.land,velocity:.35+r()*.65,id:i,color:[45+Math.floor(r()*150),55+Math.floor(r()*120),70+Math.floor(r()*110)]})}return a}
function buildPhase(c,seeds,step){const W=c.w,H=c.h,N=W*H,r=rng(c.seed+step*7993),plates=new Uint16Array(N),height=new Float32Array(N),temp=new Float32Array(N),rain=new Float32Array(N),boundary=new Uint8Array(N),river=new Uint8Array(N),vecs=new Array(N);const centers=seeds.map(s=>({...s,p:rotate(s.p,s.axis,step*c.drift*.012*s.velocity)}));
for(let y=0;y<H;y++)for(let x=0;x<W;x++){let i=y*W+x,lat=Math.PI/2-(y+.5)/H*Math.PI,lon=(x+.5)/W*Math.PI*2-Math.PI,p=vecs[i]=v3(lat,lon);let best=-9,second=-9,bid=0;for(let j=0;j<centers.length;j++){let d=dot(p,centers[j].p);if(d>best){second=best;best=d;bid=j}else if(d>second)second=d}plates[i]=bid;let plate=centers[bid],base=plate.continental?.18:-.48;let n=fractal(p,c.seed+step*1337),detail=fractal([p[2],p[0],p[1]],c.seed+457);height[i]=base+n*.27+detail*.08}
// Great-circle seam-safe boundary fields and tectonic stress
for(let y=0;y<H;y++)for(let x=0;x<W;x++){let i=y*W+x, l=y*W+(x+W-1)%W,rr=y*W+(x+1)%W,u=(Math.max(0,y-1))*W+x,d=(Math.min(H-1,y+1))*W+x;let different=plates[i]!==plates[l]||plates[i]!==plates[rr]||plates[i]!==plates[u]||plates[i]!==plates[d];if(different){boundary[i]=1;let pi=centers[plates[i]],pj=centers[plates[rr]];let conv=dot(pi.axis,pj.p)-dot(pj.axis,pi.p);let ridge=Math.abs(fractal(vecs[i],c.seed+888));if(conv>.02){height[i]+=(.32+.48*ridge)*c.mountains}else if(conv<-.02)height[i]-=.17*c.mountains;else height[i]+=.10*ridge*c.mountains}}
// climate, altitude lapse rate and latitude circulation
for(let y=0;y<H;y++)for(let x=0;x<W;x++){let i=y*W+x,lat=Math.PI/2-(y+.5)/H*Math.PI,abs=Math.abs(lat)/(Math.PI/2),e=height[i],thermal=30*(1-abs)-Math.max(0,e)*18+(noise(vecs[i],c.seed+22)-.5)*4;temp[i]=thermal;let equator=Math.exp(-Math.pow(abs/.28,2)),subtropic=.46*Math.exp(-Math.pow((abs-.48)/.18,2)),polar=.18*Math.exp(-Math.pow((abs-.90)/.20,2));rain[i]=clamp((equator+subtropic+polar)*1550+(fractal(vecs[i],c.seed+911)+.25)*380+Math.max(0,e)*220,0,2600)}
// Rivers: trace from wet highland sources toward the locally lowest neighbour; retained separately per phase.
let candidates=[];for(let i=0;i<N;i++)if(height[i]>.22&&rain[i]>720)candidates.push(i);for(let s=0;s<Math.min(34,Math.floor(c.plates*2.6));s++){if(!candidates.length)break;let cur=candidates[Math.floor(r()*candidates.length)],seen=new Set();for(let it=0;it<Math.max(W,H)*1.2;it++){if(seen.has(cur))break;seen.add(cur);river[cur]=Math.min(255,river[cur]+1);if(height[cur]<-.08)break;let x=cur%W,y=(cur/W)|0,near=[y*W+(x+W-1)%W,y*W+(x+1)%W,Math.max(0,y-1)*W+x,Math.min(H-1,y+1)*W+x];let next=near.reduce((a,b)=>height[b]+r()*.025<height[a]+r()*.025?b:a,near[0]);if(height[next]>height[cur]+.045)break;cur=next}}
// tile average + greedily merged groups summary
let tw=c.tile,th=Math.round(tw*H/W),tiles=[];for(let ty=0;ty<th;ty++)for(let tx=0;tx<tw;tx++){let x0=Math.floor(tx*W/tw),x1=Math.floor((tx+1)*W/tw),y0=Math.floor(ty*H/th),y1=Math.floor((ty+1)*H/th),sum=0,wet=0,rv=0,count=0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){let i=y*W+x;sum+=height[i];wet+=rain[i];rv+=river[i];count++}tiles.push({x:tx,y:ty,h:sum/count,r:wet/count,river:rv>0})}let groups=0,visited=new Uint8Array(tiles.length),tol=(1-c.similar)*1.5;for(let i=0;i<tiles.length;i++){if(visited[i])continue;groups++;let st=[i];visited[i]=1;while(st.length){let a=st.pop(),t=tiles[a],near=[a-1,a+1,a-tw,a+tw];for(let b of near){if(b<0||b>=tiles.length||visited[b])continue;let q=tiles[b];if(Math.abs((q.x-t.x))>1&&Math.abs(q.y-t.y)>1)continue;if(Math.abs(q.h-t.h)<tol&&Math.abs(q.r-t.r)<500&&q.river===t.river){visited[b]=1;st.push(b)}}}}
return {c,step,centers,plates,height,temp,rain,boundary,river,vecs,tiles,tw,th,groups};}
function color(w,i,mode){let h=w.height[i],t=w.temp[i],r=w.rain[i],pl=w.centers[w.plates[i]];if(mode==='plates')return pl.color;if(mode==='height'){let v=clamp((h+.8)/1.7);return h<0?[12,Math.round(75+v*70),Math.round(122+v*80)]:[Math.round(70+v*170),Math.round(80+v*120),Math.round(50+v*110)]}if(mode==='temperature'){let v=clamp((t+20)/55);return [Math.round(45+210*v),Math.round(85+120*(1-Math.abs(v-.55)*1.5)),Math.round(165-140*v)]}if(mode==='rain'){let v=clamp(r/2200);return [Math.round(210-170*v),Math.round(180+55*v),Math.round(105+130*v)]}if(mode==='rivers'){if(w.river[i])return [34,108,174];return h<0?[35,104,149]:[184,170,104]}if(mode==='terrain'){if(w.river[i])return[47,110,168];if(h<-.05)return h<-.35?[23,80,125]:[49,125,159];if(h>.65)return[235,235,226];if(h>.38)return[120,107,79];if(t<-5)return[180,193,177];if(r<350)return[201,170,94];if(r>1350)return[44,111,72];return[109,143,75]}return[0,0,0]}
function drawMap(){if(!worlds.length)return;let w=worlds[phase],image=ctx.createImageData(w.c.w,w.c.h),d=image.data;for(let i=0;i<w.height.length;i++){let c=color(w,i,layer);if(layer==='plates'&&w.boundary[i])c=[27,31,30];let o=i*4;d[o]=c[0];d[o+1]=c[1];d[o+2]=c[2];d[o+3]=255}let off=document.createElement('canvas');off.width=w.c.w;off.height=w.c.h;off.getContext('2d').putImageData(image,0,0);ctx.imageSmoothingEnabled=true;ctx.clearRect(0,0,map.width,map.height);ctx.drawImage(off,0,0,map.width,map.height);if(layer==='tiles'){drawTiles(w)}$('mapKey').innerHTML=keyFor(w);}
function drawTiles(w){ctx.strokeStyle='rgba(20,35,30,.42)';ctx.lineWidth=1;for(let x=0;x<=w.tw;x++){let xx=x*map.width/w.tw;ctx.beginPath();ctx.moveTo(xx,0);ctx.lineTo(xx,map.height);ctx.stroke()}for(let y=0;y<=w.th;y++){let yy=y*map.height/w.th;ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(map.width,yy);ctx.stroke()}}
function keyFor(w){let names={terrain:'Terrain · ocean / arid land / vegetation / peaks',plates:`${w.centers.length} tectonic plates · black = active boundary`,height:'Relative elevation · bathymetry through highland',temperature:'Annual mean surface temperature (°C)',rain:'Annual precipitation intensity (mm)',rivers:'Blue = routed downslope river network',tiles:`${w.tw} × ${w.th} tiles · ${w.groups} contiguous optimized groups`};return names[layer]||''}
function drawGlobe(){if(!worlds.length)return;let w=worlds[phase],W=globe.width,H=globe.height,im=gctx.createImageData(W,H),d=im.data,cx=W*.5,cy=H*.5,R=Math.min(W,H)*.42,rot=.55;for(let y=0;y<H;y++)for(let x=0;x<W;x++){let dx=(x-cx)/R,dy=(y-cy)/R,q=dx*dx+dy*dy;if(q>1)continue;let z=Math.sqrt(1-q),X=dx*Math.cos(rot)+z*Math.sin(rot),Z=-dx*Math.sin(rot)+z*Math.cos(rot),lat=Math.asin(-dy),lon=Math.atan2(Z,X),px=Math.floor((lon+Math.PI)/(2*Math.PI)*w.c.w)%w.c.w,py=clamp(Math.floor((Math.PI/2-lat)/Math.PI*w.c.h),0,w.c.h-1),col=color(w,py*w.c.w+px,layer),light=clamp(.58+.42*(dx*.3-dy*.7+z*.65));let o=(y*W+x)*4;d[o]=col[0]*light;d[o+1]=col[1]*light;d[o+2]=col[2]*light;d[o+3]=255}gctx.putImageData(im,0,0);gctx.strokeStyle='rgba(30,45,40,.4)';gctx.lineWidth=2;gctx.beginPath();gctx.arc(cx,cy,R,0,Math.PI*2);gctx.stroke();gctx.fillStyle='#243432';gctx.font='12px DM Mono';gctx.fillText('3D SOURCE MODEL · EQUIRECTANGULAR PROJECTION',18,26);$('mapKey').innerHTML='Interactive source globe. Surface values are sampled using 3D vectors — no map-edge seam.'}
function update(){if(view==='map')drawMap();else drawGlobe();let w=worlds[phase];if(!w)return;$('phaseTitle').textContent=phase===0?'Step 0 · Initial formation':`Step ${phase} · Drift snapshot`;$('timeLabel').textContent=(phase*w.c.years).toLocaleString()+' years';$('stepLabel').textContent=`${phase+1} / ${worlds.length}`;let land=Array.from(w.height).filter(v=>v>=-.05).length/w.height.length;let metrics=[['LAND COVER',Math.round(land*100)+'%'],['ACTIVE PLATES',w.centers.length],['MEAN TEMP',Math.round(w.temp.reduce((a,b)=>a+b,0)/w.temp.length)+'°C'],['RIVER CELLS',w.river.reduce((a,b)=>a+(b>0),0).toLocaleString()],['OPTIMIZED GROUPS',w.groups.toLocaleString()]];$('metrics').innerHTML=metrics.map(x=>`<div class="metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
function generate(){let c=cfg();$('loading').classList.remove('hidden');$('status').textContent='GENERATING SPHERICAL FIELDS';setTimeout(()=>{try{let s=makeSeeds(c);worlds=[];for(let i=0;i<c.steps;i++){ $('loadingText').textContent=`Generating independent snapshot ${i+1} / ${c.steps}…`;worlds.push(buildPhase(c,s,i))}phase=0;$('timeline').max=c.steps-1;$('timeline').value=0;update();$('status').textContent='WORLD READY · SEAM-SAFE'}catch(e){console.error(e);$('status').textContent='GENERATION ERROR'}finally{$('loading').classList.add('hidden')}},30)}
function download(){if(!worlds.length)return;let w=worlds[phase],pack={format:'atlas-forge/world-v1',planet:w.c.name,step:w.step,years:w.step*w.c.years,config:w.c,projection:'equirectangular; source topology uses unit sphere',plates:w.centers.map(p=>({id:p.id,continental:p.continental,center:p.p,driftAxis:p.axis})),resolution:[w.c.w,w.c.h],fields:{height:Array.from(w.height),temperatureC:Array.from(w.temp),precipitationMm:Array.from(w.rain),plateId:Array.from(w.plates),rivers:Array.from(w.river)},tilemap:{resolution:[w.tw,w.th],optimizedGroups:w.groups,tiles:w.tiles}};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(pack)],{type:'application/json'}));a.download=`${w.c.name.replace(/[^a-z0-9]/gi,'_')}_step_${w.step}.json`;a.click();URL.revokeObjectURL(a.href)}
[['tilt','tiltOut',v=>v+'°'],['plates','platesOut'],['land','landOut',v=>v+'%'],['mountains','mountOut',v=>v+'%'],['micro','microOut'],['steps','stepsOut'],['drift','driftOut',v=>(v/100).toFixed(2)+'°'],['similarity','similarOut',v=>v+'%']].forEach(([a,b,f])=>$(a).oninput=()=>$(b).value=f?f($(a).value):$(a).value);
$('generate').onclick=generate;$('randomize').onclick=()=>{$('seed').value=Math.floor(Math.random()*9e8)+1;generate()};$('export').onclick=download;$('timeline').oninput=e=>{phase=+e.target.value;update()};$('layers').onclick=e=>{if(e.target.dataset.layer){layer=e.target.dataset.layer;document.querySelectorAll('#layers button').forEach(b=>b.classList.toggle('active',b===e.target));update()}};document.querySelector('.view-tabs').onclick=e=>{if(e.target.dataset.view){view=e.target.dataset.view;document.querySelectorAll('.view-tabs button').forEach(b=>b.classList.toggle('active',b===e.target));map.style.display=view==='map'?'block':'none';globe.style.display=view==='sphere'?'block':'none';update()}};generate();
